spring:
  application:
    name: Student Management System
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/liquibase-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.sendgrid.net
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui: path=/swagger-ui.html

sendgrid:
  api:
    key: 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

logging:
  file:
    path: logs/
    name: logs/application.log
